sudo: required
dist: bionic
langauge: python
virtualenv:
  system_site_packages: true
python:
  - '3.6'
install:
  - pip install -e .
script: pytest
after_script: 
  - cd ~
  - codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)